name: Brioche
favicon: null
layout_spectrum: 0.23554
typography_spectrum: 0.73554
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c1d1b'
    - '#fefefe'
    - '#000000'
    - '#959595'
    - '#5d5d5d'
  brandStrength: 0.17167197982780635
  lightness: 0.8959000788163394
  saturation: 0.6327113925945014
  rhythmicContrast: 0.6808370708022267
purpose: []
